# Form implementation generated from reading ui file 'c:\Users\Arango\Mi unidad\PROGRAMACION\POSICIONES DEPOSITO\CONSOLIDADO\MOVIMIENTOS\modules\views\login\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(5)
        Form.setFont(font)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0  rgb(212, 131, 131), stop:1 rgb(170, 30, 25));\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.input_contrasena = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.input_contrasena.setFont(font)
        self.input_contrasena.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.input_contrasena.setStyleSheet("background-color: rgb(255, 251, 212);")
        self.input_contrasena.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.input_contrasena.setText("")
        self.input_contrasena.setMaxLength(30)
        self.input_contrasena.setCursorPosition(0)
        self.input_contrasena.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_contrasena.setDragEnabled(False)
        self.input_contrasena.setClearButtonEnabled(True)
        self.input_contrasena.setObjectName("input_contrasena")
        self.gridLayout.addWidget(self.input_contrasena, 2, 0, 1, 1)
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_login.setStyleSheet("    background-color: rgb(170, 30, 25);\n"
"    color: rgb(255, 255, 255);\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 4, 0, 1, 1)
        self.input_usuario = QtWidgets.QLineEdit(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.input_usuario.setFont(font)
        self.input_usuario.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.input_usuario.setStyleSheet("background-color: rgb(255, 251, 212);")
        self.input_usuario.setInputMask("")
        self.input_usuario.setText("")
        self.input_usuario.setMaxLength(32767)
        self.input_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_usuario.setDragEnabled(False)
        self.input_usuario.setClearButtonEnabled(True)
        self.input_usuario.setObjectName("input_usuario")
        self.gridLayout.addWidget(self.input_usuario, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.input_usuario, self.input_contrasena)
        Form.setTabOrder(self.input_contrasena, self.btn_login)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700; font-style:italic; color:#ffffff;\">Bienvenido</span></p></body></html>"))
        self.input_contrasena.setPlaceholderText(_translate("Form", "Ingrese la contraseña"))
        self.btn_login.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_login.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_login.setText(_translate("Form", "Iniciar Sesión"))
        self.input_usuario.setPlaceholderText(_translate("Form", "Ingrese el usuario"))
